# POC: allow IPv6 forwarding for Thread border routing, minimize globals
net.ipv6.conf.all.forwarding=1
# Default reject RAs globally; uplink interfaces may override
net.ipv6.conf.default.accept_ra=0
net.ipv6.conf.all.accept_ra=0
